# Generated by Django 6.0.6 on 2026-07-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_menu_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItems',
        ),
    ]
